FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
COPY proto ./dist/proto

RUN npm run build

WORKDIR /app/dist/apps/api-gateway

EXPOSE 4000

CMD ["node", "main.js"]
