FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
COPY proto ./dist/proto

RUN npm run build

WORKDIR /app/dist/apps/auth-service

EXPOSE 50051

CMD ["node", "main.js"]
